### ISSUE TITLE
Target publish?

### ISSUE THREAD

**Issue by DejanMilicic** [Jlll1/Sutil-Template#11]
Target `publish` is missing.
What would be recommended way to publish for production deployment?

**Comment by Jlll1** [comment]
I purposefully omitted adding a `publish` target, because I feel like a template shouldn't really include that. There's just so many ways you can handle deployment, that it most likely would end up as dead code, and that's something I wanted to avoid. I think the template should contain just the bare minimum, to allow you to build on top of, but not more, so that no code needs to be removed by the user or preferably even end up unused.

Now when it comes to a good starting point, I'd suggest checking out the official [Safe-Template](https://github.com/SAFE-Stack/SAFE-template), which has an `azure` target that handles deployment using [Farmer](https://github.com/CompositionalIT/farmer). 
Check it out:
https://github.com/SAFE-Stack/SAFE-template/blob/eee66e47d6e7403495dcfb60eb4e7c3a982b5785/Content/default/Build.fs#L31-L46

**Comment by DejanMilicic** [comment]
I understood the reasoning, and I completely agree with you. The template should cover the lowest common denominator.
Thanx for the pointer!
